artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://huggingface.co/datasets/lmsys/lmsys-chat-1m
  local_data_file_train: artifacts/data_ingestion/train
  local_data_file_test: artifacts/data_ingestion/test
  dataset: lmsys/lmsys-chat-1m

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  transformed_data_path_train: artifacts/data_transformation/train
  transformed_data_path_test: artifacts/data_transformation/test
  tokenizer_name: gpt2

model_trainer:
  root_dir: artifacts/model_trainer
  data_path_train: artifacts/data_transformation/train
  data_path_test: artifacts/data_transformation/test
  model_ckpt: gpt2
  model_save_path: artifacts/model_trainer/gpt2-trained

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/test
  model_path: artifacts/model_trainer/gpt2-trained
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
